spring:
  jpa:
    database: mysql
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false
  datasource:
    url: jdbc:mysql://mysql:3306/portfolio
    username: root
    password: ENC(5QkblP/F+yDvz11YgjH+byOIIpu/AuA)
    driver-class-name: com.mysql.cj.jdbc.Driver