spring:
  batch:
    job:
      names: ${job.name:NONE}
    jdbc:
      initialize-schema: always

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MySQL
    username: sa
    password:

  sql:
    init:
      mode: ALWAYS
