server:
  port: ${port:2222}

spring:
  application:
    name: first-service

  devtools:
    restart:
      exclude: static/**

  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      authentication-database: admin
      database: microservices

logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} %-5level %logger{36} - %msg%n"
    file: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  level:
    org:
      springframework:
        web: DEBUG

# open-api
springdoc:
  version: '@project.version@'
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /swagger-ui.html
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true
    doc-expansion: none
  paths-to-match:
    - /api/**

name: first-service
my:
  servers:
    - dev.bar.com
    - foo.bar.com

# actuator
management:
  security:
    enabled: false

  endpoint:
    health:
      enabled: true
      show-details: always
